version: '3'

services:
  
  mongo:
    image: mongo:5
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokemon
    volumes:
      - ./mongo/:/data/db